// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iERP.Modules.Engines.Bridge.Infrastructure;

#nullable disable

namespace iERP.Migrations.Migrations.Bridge
{
    [DbContext(typeof(BridgeDbContext))]
    partial class BridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bridge")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iERP.Modules.Engines.Bridge.Domain.BridgeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceEntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_entity_name");

                    b.Property<string>("TargetEntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_entity_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bridge_definitions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bridge_definitions_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_bridge_definitions_tenant_id_code");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("ix_bridge_definitions_tenant_id_is_deleted");

                    b.ToTable("bridge_definitions", "bridge");
                });

            modelBuilder.Entity("iERP.Modules.Engines.Bridge.Domain.BridgeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BridgeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bridge_definition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("SourceRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_record_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_record_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bridge_logs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bridge_logs_tenant_id");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("ix_bridge_logs_tenant_id_is_deleted");

                    b.HasIndex("TenantId", "BridgeDefinitionId", "SourceRecordId")
                        .HasDatabaseName("ix_bridge_logs_tenant_id_bridge_definition_id_source_record_id");

                    b.ToTable("bridge_logs", "bridge");
                });

            modelBuilder.Entity("iERP.Modules.Engines.Bridge.Domain.BridgeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BridgeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bridge_definition_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_field");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_field");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TransformExpression")
                        .HasColumnType("text")
                        .HasColumnName("transform_expression");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bridge_mappings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bridge_mappings_tenant_id");

                    b.HasIndex("TenantId", "IsDeleted")
                        .HasDatabaseName("ix_bridge_mappings_tenant_id_is_deleted");

                    b.HasIndex("TenantId", "BridgeDefinitionId", "SourceField")
                        .HasDatabaseName("ix_bridge_mappings_tenant_id_bridge_definition_id_source_field");

                    b.ToTable("bridge_mappings", "bridge");
                });
#pragma warning restore 612, 618
        }
    }
}
