<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>iERP.Modules.HR</RootNamespace>
    <AssemblyName>iERP.Modules.HR</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\iERP.SharedKernel\iERP.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\iERP.Application.Abstractions\iERP.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\iERP.Infrastructure\iERP.Infrastructure.csproj" />
  </ItemGroup>
</Project>
